Repository codingBottle/Helfy-iOS, pull requests merged in 2023-11, with the labels that each got.

#17 [#13] 구글 로그인 연결
  Helfy.xcodeproj/project.pbxproj
  Helfy/Controller/Login/FirebaseAuth.swift
  Helfy/Controller/Login/GoogleSignIn.swift
  Helfy/Controller/LoginViewController.swift
Labels: ✨ Feat, 🆘 HotFix

#21 [#14] 네비게이션 버튼 구현
  Helfy.xcodeproj/project.pbxproj
  Helfy/AppDelegate.swift
  Helfy/Controller/NavigationController.swift
  Helfy/Controller/WriteViewController.swift
  Helfy/Model/WriteModel.swift
  Helfy/SceneDelegate.swift
  Helfy/View/NaviButtonView.swift
  Helfy/View/WriteView.swift
Labels: ✨ Feat

#25 [#24] 하단탭 구현
  Helfy.xcodeproj/project.pbxproj
  Helfy/Controller/CommunityViewController.swift
  Helfy/Controller/HomeViewController.swift
  Helfy/Controller/TabBarViewController.swift
  Helfy/View/BottomTabBarView.swift
Labels: ✨ Feat

#28 [#23] setting 변경
  Helfy.xcodeproj/project.pbxproj
Labels: 👩🏻‍💻 Working, ⚙️ Setting

#20 [#18] 애플 로그인 구현
  Helfy.xcodeproj/project.pbxproj
  Helfy.xcodeproj/xcshareddata/xcschemes/Helfy.xcscheme
  Helfy/AppDelegate.swift
  Helfy/Controller/Login/AppleSignIn.swift
  Helfy/Controller/Login/FirebaseAuth.swift
  Helfy/Controller/LoginViewController.swift
  Helfy/Helfy.entitlements
Labels: ✨ Feat

#34 [#29] 마이페이지 구현
  Helfy.xcodeproj/project.pbxproj
  Helfy/Controller/MypageViewController.swift
  Helfy/Model/MypageModel.swift
  Helfy/View/MypageView.swift
Labels: ✨ Feat

#22 [#16] 카테고리 버튼 구현
  Helfy.xcodeproj/project.pbxproj
  Helfy/AppDelegate.swift
  Helfy/Assets.xcassets/AccentColor.colorset/Contents.json
  Helfy/Assets.xcassets/가뭄.imageset/Contents.json
  Helfy/Assets.xcassets/가뭄.imageset/가뭄.png
  Helfy/Assets.xcassets/강풍.imageset/Contents.json
  Helfy/Assets.xcassets/강풍.imageset/강풍.png
  Helfy/Assets.xcassets/낙뢰.imageset/Contents.json
  Helfy/Assets.xcassets/낙뢰.imageset/free-icon-lightning-7105134.png
  Helfy/Assets.xcassets/녹조.imageset/Contents.json
  Helfy/Assets.xcassets/녹조.imageset/녹조.png
  Helfy/Assets.xcassets/대설.imageset/Contents.json
  Helfy/Assets.xcassets/대설.imageset/대설.png
  Helfy/Assets.xcassets/산사태.imageset/Contents.json
  Helfy/Assets.xcassets/산사태.imageset/산사태.png
  Helfy/Assets.xcassets/우주전파재난.imageset/Contents.json
  Helfy/Assets.xcassets/우주전파재난.imageset/우주전파재난.png
  Helfy/Assets.xcassets/자연우주물체추락.imageset/Contents.json
  Helfy/Assets.xcassets/자연우주물체추락.imageset/자연우주물체추락.png
  Helfy/Assets.xcassets/적조.imageset/Contents.json
  Helfy/Assets.xcassets/적조.imageset/적조.png
  Helfy/Assets.xcassets/지진.imageset/Contents.json
  Helfy/Assets.xcassets/지진.imageset/지진.png
  Helfy/Assets.xcassets/지진해일.imageset/Contents.json
  Helfy/Assets.xcassets/지진해일.imageset/지진해일.png
  Helfy/Assets.xcassets/침수.imageset/Contents.json
  Helfy/Assets.xcassets/침수.imageset/침수.png
  Helfy/Assets.xcassets/태풍.imageset/Contents.json
  Helfy/Assets.xcassets/태풍.imageset/태풍.png
  Helfy/Assets.xcassets/폭염.imageset/Contents.json
  Helfy/Assets.xcassets/폭염.imageset/폭염.png
  Helfy/Assets.xcassets/풍랑.imageset/Contents.json
  Helfy/Assets.xcassets/풍랑.imageset/풍랑.png
  Helfy/Assets.xcassets/한파.imageset/Contents.json
  Helfy/Assets.xcassets/한파.imageset/한파.png
  Helfy/Assets.xcassets/해수면상승.imageset/Contents.json
  Helfy/Assets.xcassets/해수면상승.imageset/해수면상승.png
  Helfy/Assets.xcassets/해일.imageset/Contents.json
  Helfy/Assets.xcassets/해일.imageset/해일.png
  Helfy/Assets.xcassets/호우.imageset/Contents.json
  Helfy/Assets.xcassets/호우.imageset/호우.png
  Helfy/Assets.xcassets/홍수.imageset/Contents.json
  Helfy/Assets.xcassets/홍수.imageset/홍수.png
  Helfy/Assets.xcassets/화산폭발.imageset/Contents.json
  Helfy/Assets.xcassets/화산폭발.imageset/화산폭발.png
  Helfy/Assets.xcassets/황사.imageset/Contents.json
  Helfy/Assets.xcassets/황사.imageset/황사.png
  Helfy/Controller/QuizViewController.swift
  Helfy/View/CategoryView.swift
  Helfy/View/QuizView.swift
  Helfy/View/testView.swift
Labels: ✨ Feat, 👩🏻‍💻 Working

#39 [#30] feat : 여러 인증 제공업체 연결 및 로그아웃 구현
  Helfy.xcodeproj/project.pbxproj
  Helfy/AppDelegate.swift
  Helfy/Controller/Login/AppleSignIn.swift
  Helfy/Controller/Login/FirebaseAuth.swift
  Helfy/Controller/Login/GoogleSignIn.swift
  Helfy/Controller/Login/LoginViewController.swift
  Helfy/Controller/LoginViewController.swift
  Helfy/Controller/MainViewController.swift
  Helfy/Model/UserModel.swift
  Helfy/SceneDelegate.swift
Labels: ✨ Feat
