Repository codingBottle/Helfy-iOS, pull requests merged in 2023-10, with the labels that each got.

#8 [#6] 프로젝트 세팅
  Helfy.xcodeproj/project.pbxproj
  Helfy/Base.lproj/Main.storyboard
  Helfy/Info.plist
  Helfy/SceneDelegate.swift
Labels: 🆘 HotFix

#9 [#6] MVC 패턴으로 폴더링 작업
  Helfy.xcodeproj/project.pbxproj
  Helfy/Controller/ViewController.swift
Labels: 🆘 HotFix

#10 [#6] 구글 로그인 기능 추가
  Helfy.xcodeproj/project.pbxproj
  Helfy.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  Helfy.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Helfy/AppDelegate.swift
  Helfy/Controller/LoginViewController.swift
  Helfy/Controller/ViewController.swift
  Helfy/GoogleService-Info.plist
  Helfy/Info.plist
  Helfy/SceneDelegate.swift
Labels: ✨ Feat, 👩🏻‍💻 Working

#11 [#5] 퀴즈뷰 상단탭 구현
  Helfy.xcodeproj/project.pbxproj
  Helfy/Controller/QuizViewController.swift
  Helfy/Controller/ViewController.swift
  Helfy/Model/RankingModel.swift
  Helfy/SceneDelegate.swift
  Helfy/View/RankingView.swift
Labels: ✨ Feat

#12 [#7] 제보하기 기능 구현
  Helfy.xcodeproj/project.pbxproj
  Helfy/AppDelegate.swift
  Helfy/Controller/ReportViewController.swift
  Helfy/Info.plist
  Helfy/SceneDelegate.swift
  Helfy/View/ReportView.swift
Labels: ✨ Feat

#19 [#18] 애플 로그인 연결
  Helfy.xcodeproj/project.pbxproj
  Helfy.xcodeproj/xcshareddata/xcschemes/Helfy.xcscheme
  Helfy/AppDelegate.swift
  Helfy/Controller/LoginViewController.swift
  Helfy/Info.plist
Labels: ✨ Feat, 👩🏻‍💻 Working
